services:
  wsd_recruiting_rest_api:
    image: sksla123/wsd_recruiting_rest_api:latest
    container_name: wsd_recruiting_rest_api
    environment:
      # 여기서 원하는 모드 선택 가능
      # 내부 데이터 베이스를 사용하는 모드

      # 웹 스크랩 부터 데이터를 다시 넣습니다. (data 폴더에 아무것도 없어도 작동합니다.)
      # - CONTAINER_INIT_MODE=FROM_SCRAPPING  

      # DB 초기화부터  시작합니다. data 폴더에 'selected_codetable_data_backup.pkl'과 'selected_data_backup.pkl' 파일을 반드시 넣어주세요.
      # 이 파일은 init_database_by_web_scrapping/scrap.py의 결과물과 같습니다.
      # - CONTAINER_INIT_MODE=FROM_DB_INITIALIZING

      # dump.sql을 가지고 초기화합니다.
      # data 폴더에 dump.sql 파일을 반드시 넣어주세요.
      - CONTAINER_INIT_MODE=USE_INTERNAL_DB


      # 외부 데이터 베이스를 사용하는 모드
      # data 폴더에 .env 파일을 반드시 넣어주세요. (.env 형식은 README.md에 정의된 내용을 참조하세요.)
      # - CONTAINER_INIT_MODE=USE_EXTERNAL_DB
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - ./data:/DATA
    ports:
      - "3000:5000" # 적절한 포트포워딩 규칙을 설정하세요.